server:
  port: 8080

spring:
  config:
    import: "optional:file:.env[.properties]"
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}


jwt:
  access-key: ${JWT_ACCESS_KEY}
  refresh-key: ${JWT_REFRESH_KEY}
  access-expiration-minutes: ${JWT_ACCESS_EXPIRATION_MINUTES}
  refresh-expiration-days: ${JWT_REFRESH_EXPIRATION_DAYS}